# Generated by Django 4.2 on 2023-04-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="photos/%y/%m/%d")),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
