# Generated by Django 4.2 on 2023-04-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-price"], "verbose_name": "Product_tb"},
        ),
    ]
