# Generated by Django 4.2 on 2023-04-25 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="created",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="test", name="time", field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="test", name="date", field=models.DateField(),
        ),
    ]
