# Generated by Django 4.2 on 2023-04-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_lg"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisterForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="lg",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
