# Generated by Django 4.2 on 2023-04-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_rename_registerform_register"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
